version: '3.4'

services:
  api.db:
    image: postgres:15
    container_name: api_db
    command: postgres -c 'max_connections=200'
    environment:
      - POSTGRES_DB=ApiDB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=super_secret_password
    volumes:
      - api_db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 45s
      timeout: 30s
      retries: 5
      start_period: 30s

  utils.pgadmin:
    image: dpage/pgadmin4
    container_name: utils_pgadmin
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: user@123.com
      PGADMIN_DEFAULT_PASSWORD: user@123
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - api.db

  identity.keycloak:
    image: quay.io/keycloak/keycloak:23.0.4
    container_name: identity_keycloak
    command: --verbose start-dev
    environment:
      KC_LOG_LEVEL: ERROR
      KC_DB: postgres
      KC_DB_URL_HOST: identity.keycloak.db
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: super_secret_password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: super_secret_password
    ports:
      - 8080:8080
    depends_on:
      identity.keycloak.db:
        condition: service_healthy

  identity.keycloak.db:
    image: postgres:15
    container_name: identity_keycloak_db
    command: postgres -c 'max_connections=200'
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=super_secret_password
    volumes:
      - keycloak_db:/var/lib/postgresql/data
    ports:
      - 5532:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 45s
      timeout: 30s
      retries: 5
      start_period: 30s

volumes:
  api_db:
  keycloak_db:
  pgadmin_data: